-- ============================================================
-- Tabela "despesas" — Financeiro da Clínica (clínica + pessoal)
-- Rodar UMA vez no Supabase → SQL Editor → New query → Run.
-- Cria a tabela que faltava: por isso os débitos "sumiam".
-- Mesma estrutura das outras tabelas do app (user_id + dados jsonb).
-- ============================================================

create table if not exists public.despesas (
  id      bigint generated by default as identity primary key,
  user_id text,
  dados   jsonb
);

alter table public.despesas enable row level security;

-- Acesso pela chave anônima (mesmo padrão das tabelas que já funcionam)
drop policy if exists "despesas_anon_all" on public.despesas;
create policy "despesas_anon_all"
  on public.despesas for all
  to anon
  using (true)
  with check (true);
