-- Tabela de Diplomas/Certificados (seção "Sobre / Formação")
-- Rode isso no Supabase (SQL Editor) uma única vez antes de usar o upload de diplomas.

create table if not exists diplomas (
  id bigint generated by default as identity primary key,
  user_id text not null default 'montgomery',
  dados jsonb not null
);

alter table diplomas enable row level security;
create policy "permitir tudo diplomas" on diplomas for all using (true) with check (true);
